language: java
notifications:
  email:
    recipients:
      - akamen@blackducksoftware.com
      - jrichard@blackducksoftware.com

install: true
script:
  - mvn install
after_success:
  - mvn clean test jacoco:report coveralls:report
