language: java

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - akamen@blackducksoftware.com
      - jrichard@blackducksoftware.com
      - psantos@blackducksoftware.com
      - ekerwin@blackducksoftware.com

install: true
script:
  - mvn clean package com.blackducksoftware.integration:hub-maven-plugin:1.4.0:createHubOutput -DskipTests
after_success:
  - bash <(curl -s https://test.duckbuild.io/bash/travis) ./target/blackduck/blackduck-hub_bdio.jsonld
